Error: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/Users/hans/Projects/Usach/geospatialWebapp/backend/connectrpc_server.py", line 231, in <module>
    asyncio.run(serve())
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/hans/.pyenv/versions/3.9.16/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/hans/Projects/Usach/geospatialWebapp/backend/connectrpc_server.py", line 209, in serve
    await server.start()
TypeError: object NoneType can't be used in 'await' expression
